import { createFileRoute } from "@tanstack/react-router"
import { useState, useEffect } from "react"
export const Route = createFileRoute("/")({ component: FreshBusiness })

function FreshBusiness(){
  const ADMIN="fscnajmul2026@gmail.com"
  const [email,setEmail]=useState("")
  const [user,setUser]=useState<any>(null)
  const [page,setPage]=useState("home")
  const [cat,setCat]=useState("fb_cookies")

  const [ads,setAds]=useState({top:"Top Small Ad - Always On Top",middle:"Middle Big Ad - Always In Middle - 728x90",task:"Task 10s Video Ad"})
  const [numbers,setNumbers]=useState({bkash:"017XXXXXXXX Personal",usdt:"TXYZ...TRC20 Binance"})
  const [plans,setPlans]=useState([{id:1,name:"Starter",price:500,active:true},{id:2,name:"Pro",price:1500,active:true},{id:3,name:"VIP",price:5000,active:true}])

  const [tasks,setTasks]=useState<any[]>([
    {id:101,cat:"fb_cookies",title:"Facebook Cookies Sell",reward:180,active:true,fields:"c_user,xs Cookie,User Agent,FB Profile Link",needPkg:true},
    {id:102,cat:"ig_cookies",title:"Instagram Cookies Sell",reward:200,active:true,fields:"sessionid Cookie,Username,Password",needPkg:true},
    {id:103,cat:"social_visit",title:"Social Visit - Telegram Channel Join",reward:15,active:true,fields:"Telegram Link,Join Screenshot Proof",needPkg:false},
    {id:104,cat:"social_visit",title:"Social Visit - Facebook Page Like + Follow",reward:20,active:true,fields:"FB Page Link,Like Screenshot",needPkg:false},
    {id:105,cat:"social_visit",title:"Social Visit - Instagram Video Dekha + Like",reward:25,active:true,fields:"Insta Video Link,View + Like Screenshot",needPkg:false},
    {id:106,cat:"social_visit",title:"Social Visit - YouTube Video View + Subscribe",reward:30,active:true,fields:"YouTube Link,Subscribe Screenshot",needPkg:false},
    {id:107,cat:"visa",title:"Visa Card Service / Visa Sell",reward:500,active:true,fields:"Visa Card Number,Expiry,CVV / Application Info",needPkg:true},
    {id:108,cat:"gmail",title:"Gmail Sell",reward:120,active:true,fields:"Gmail,Password,Recovery",needPkg:true},
    {id:109,cat:"coin",title:"USDT Coin Sell",reward:100,active:true,fields:"Amount,Hash,Address",needPkg:true},
  ])
  const [subs,setSubs]=useState<any[]>([])
  const [deps,setDeps]=useState<any[]>([])
  const [features,setFeatures]=useState({fb_cookies:true,ig_cookies:true,social_visit:true,visa:true,gmail:true,coin:true,facebook:true} as any)

  const [dM,setDM]=useState("bkash")
  const [dA,setDA]=useState("")
  const [dT,setDT]=useState("")
  const [count,setCount]=useState(10)
  const [adOpen,setAdOpen]=useState(false)
  const [canDo,setCanDo]=useState(false)
  const [active,setActive]=useState<any>(null)
  const [form,setForm]=useState<any>({})

  useEffect(()=>{
    const u=localStorage.getItem("fresh_user"); if(u) setUser(JSON.parse(u))
    const d=JSON.parse(localStorage.getItem("fresh_data")||"{}")
    if(d.ads) setAds(d.ads); if(d.tasks) setTasks(d.tasks); if(d.deps) setDeps(d.deps); if(d.subs) setSubs(d.subs); if(d.features) setFeatures(d.features); if(d.numbers) setNumbers(d.numbers); if(d.plans) setPlans(d.plans)
  },[])
  const save=(ex:any={})=>{localStorage.setItem("fresh_data",JSON.stringify({ads,tasks,deps,subs,features,numbers,plans,...ex}))}
  useEffect(()=>{if(adOpen&&count>0){const t=setTimeout(()=>setCount(c=>c-1),1000); return()=>clearTimeout(t)} if(count===0) setCanDo(true)},[adOpen,count])

  const login=()=>{if(!email) return alert("Email দাও"); let all=JSON.parse(localStorage.getItem("fresh_all")||"[]"); let f=all.find((x:any)=>x.email===email); let u=f||{email,accId:"#BIZ"+Math.floor(10000+Math.random()*90000),balance:0,plan:null}; if(!f){all=[...all,u]; localStorage.setItem("fresh_all",JSON.stringify(all))} localStorage.setItem("fresh_user",JSON.stringify(u)); setUser(u)}
  const isAdmin=user?.email===ADMIN
  const filtered=tasks.filter(t=>t.cat===cat&&t.active&&(features as any)[t.cat])

  if(!user) return <div className="min-h-screen bg-black flex items-center justify-center p-6"><div className="bg-white w-full max-w-sm rounded-[32px] p-8"><p className="text-[10px] tracking-[3px] text-gray-400">FRESH BUSINESS</p><h1 className="text-3xl font-black mt-1">Business Pro Max</h1><p className="text-xs mt-2">Visa + FB Cookies + IG Cookies + Social Visit + Ad Always</p><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" className="w-full mt-6 border-2 border-black rounded-full p-4 text-sm"/><button onClick={login} className="w-full mt-4 bg-black text-white py-4 rounded-full font-black">LOGIN</button><p className="text-[10px] text-center mt-3">{ADMIN}</p></div></div>

  if(page==="admin"&&isAdmin){
    return <div className="min-h-screen bg-white p-4 pb-32">
      <button onClick={()=>setPage("home")} className="bg-black text-white px-5 py-2 rounded-full text-sm">← Back</button>
      <h1 className="text-xl font-black mt-4">ADMIN - Fresh Full Control</h1><p className="text-xs text-green-600 font-bold">{ADMIN} Only</p>

      <div className="bg-black text-white rounded-[24px] p-5 mt-4"><h3 className="font-black">📢 Ad Control - Top + Middle Always Must Be</h3><p className="text-[10px] mt-3 opacity-60">Top Small Ad - Always On Top</p><textarea value={ads.top} onChange={e=>{const n={...ads,top:e.target.value}; setAds(n); save({ads:n})}} className="w-full bg-white/10 border rounded-xl p-2 mt-1 text-xs h-14" placeholder="Top Ad - Adsterra Code"/><p className="text-[10px] mt-3 opacity-60">Middle Big Ad - Always In Middle</p><textarea value={ads.middle} onChange={e=>{const n={...ads,middle:e.target.value}; setAds(n); save({ads:n})}} className="w-full bg-white/10 border rounded-xl p-2 mt-1 text-xs h-20" placeholder="Middle Ad 728x90"/><p className="text-[10px] mt-3 opacity-60">Task 10s Ad</p><textarea value={ads.task} onChange={e=>{const n={...ads,task:e.target.value}; setAds(n); save({ads:n})}} className="w-full bg-white/10 border rounded-xl p-2 mt-1 text-xs h-14" placeholder="Task Ad"/></div>

      <div className="bg-white border-2 rounded-[24px] p-5 mt-4"><h3 className="font-black">🎛️ NEW TASKS CONTROL - Visa + FB Cookies + IG Cookies + Social Visit</h3><p className="text-[10px] text-gray-500">এখান থেকে ON/OFF + Price + Field সব কন্ট্রোল</p>
        <div className="grid grid-cols-2 gap-2 mt-3">{Object.keys(features).map(k=><div key={k} className="bg-gray-50 border p-3 rounded-xl flex justify-between items-center"><div><p className="text-[11px] font-black uppercase">{k.replace("_"," ")}</p><p className="text-[9px]">{(features as any)[k]?"🟢 ON":"🔴 OFF"}</p></div><button onClick={()=>{const nf={...features,[k]:!(features as any)[k]}; setFeatures(nf); save({features:nf})}} className={`px-3 py-1 rounded-full text-[10px] font-black ${(features as any)[k]?"bg-green-600 text-white":"bg-red-600 text-white"}`}>{(features as any)[k]?"ON":"OFF"}</button></div>)}</div>
        <div className="mt-5 space-y-3 max-h-[500px] overflow-auto">{tasks.map(t=><div key={t.id} className="bg-gray-50 border-2 p-4 rounded-xl text-xs"><div className="flex justify-between items-start"><div><p className="font-black">[{t.cat.toUpperCase()}] {t.title}</p><p className="text-[11px] mt-1">Reward: ৳{t.reward} | Fields: {t.fields}</p><p className="text-[10px] mt-1">{t.active?"🟢 Active - User দেখবে":"🔴 Inactive"} | {t.needPkg?"🔒 Plan লাগবে":"✅ Free"}</p></div><span className="bg-black text-white px-2 py-1 rounded-full text-[10px]">৳{t.reward}</span></div><div className="flex gap-1 mt-3 flex-wrap"><button onClick={()=>{const r=prompt("New Reward ৳?",String(t.reward)); if(r){const nt=tasks.map(x=>x.id===t.id?{...x,reward:Number(r)}:x); setTasks(nt); save({tasks:nt})}}} className="bg-black text-white px-3 py-1.5 rounded-full text-[10px]">Price Edit</button><button onClick={()=>{const f=prompt("Fields Edit",t.fields); if(f){const nt=tasks.map(x=>x.id===t.id?{...x,fields:f}:x); setTasks(nt); save({tasks:nt})}}} className="bg-blue-600 text-white px-3 py-1.5 rounded-full text-[10px]">Field Edit</button><button onClick={()=>{const nt=tasks.map(x=>x.id===t.id?{...x,active:!x.active}:x); setTasks(nt); save({tasks:nt})}} className={`px-3 py-1.5 rounded-full text-[10px] font-bold ${t.active?"bg-green-600 text-white":"bg-red-600 text-white"}`}>{t.active?"ON":"OFF"}</button><button onClick={()=>{const nt=tasks.filter(x=>x.id!==t.id); setTasks(nt); save({tasks:nt})}} className="bg-red-100 text-red-600 px-3 py-1.5 rounded-full text-[10px]">Delete</button></div></div>)}</div>
        <button onClick={()=>{const cat=prompt("Category: fb_cookies / ig_cookies / social_visit / visa / gmail / coin"); const title=prompt("Title ex: Facebook Cookies Sell"); const reward=prompt("Reward ৳?"); const fields=prompt("Fields কি লাগবে? ex: Cookies,Link,Screenshot"); if(cat&&title){const nt=[...tasks,{id:Date.now(),cat,title,reward:Number(reward||0),active:true,fields:fields||"Details",needPkg:confirm("Plan লাগবে? OK=Yes")}]; setTasks(nt); save({tasks:nt})}}} className="w-full mt-5 bg-[#0f7a4a] text-white py-3 rounded-full text-xs font-black">+ New Task Add - Visa / FB Cookies / IG Cookies / Social Visit</button>
      </div>

      <div className="bg-green-50 border-2 border-green-300 rounded-[24px] p-5 mt-4"><h3 className="font-black">📥 Receive Inbox - Cookies, Social Visit, Visa সব এখানে আসবে</h3>{subs.length===0?<p className="text-xs text-gray-400 mt-2">No submissions yet</p>:subs.map((s:any)=><div key={s.id} className="bg-white border-2 p-3 rounded-xl mt-3 text-xs"><p className="font-black">[{s.cat}] {s.title} - {s.email} ৳{s.reward}</p><div className="bg-gray-50 p-3 rounded-xl mt-2">{Object.keys(s.data).map(k=><p key={k} className="mt-1"><b>{k}:</b> <span className="break-all">{s.data[k]}</span></p>)}</div><button onClick={()=>{const nd=subs.map((x:any)=>x.id===s.id?{...x,status:"approved"}:x); setSubs(nd); save({subs:nd}); let all=JSON.parse(localStorage.getItem("fresh_all")||"[]"); all=all.map((u:any)=>u.email===s.email?{...u,balance:u.balance+s.reward}:u); localStorage.setItem("fresh_all",JSON.stringify(all))}} className="bg-green-600 text-white px-4 py-2 rounded-full mt-3 font-bold">Approve & Pay ৳{s.reward} - Receive Done</button></div>)}</div>

      <div className="bg-black text-white rounded-[24px] p-5 mt-4"><h3 className="font-black">💳 Deposit Numbers</h3><input value={numbers.bkash} onChange={e=>{const n={...numbers,bkash:e.target.value}; setNumbers(n); save({numbers:n})}} className="w-full bg-white/10 border rounded-full p-3 mt-2 text-xs" placeholder="Bkash"/><input value={numbers.usdt} onChange={e=>{const n={...numbers,usdt:e.target.value}; setNumbers(n); save({numbers:n})}} className="w-full bg-white/10 border rounded-full p-3 mt-2 text-xs" placeholder="USDT Binance"/></div>
      <div className="bg-yellow-50 border-2 rounded-[24px] p-5 mt-4"><h3 className="font-black">💰 Deposit Requests</h3>{deps.filter((d:any)=>d.status==="pending").map((d:any)=><div key={d.id} className="bg-white p-3 rounded-xl mt-2 text-xs"><p>{d.email} ৳{d.amount} Trx:{d.trx}</p><button onClick={()=>{const nd=deps.map((x:any)=>x.id===d.id?{...x,status:"approved"}:x); setDeps(nd); save({deps:nd}); let all=JSON.parse(localStorage.getItem("fresh_all")||"[]"); all=all.map((u:any)=>u.email===d.email?{...u,balance:u.balance+d.amount}:u); localStorage.setItem("fresh_all",JSON.stringify(all))}} className="bg-black text-white px-3 py-1 rounded-full mt-1">Accept</button></div>)}</div>
    </div>
  }

  return <div className="min-h-screen bg-[#f5f5f5] pb-28">
    <div className="bg-yellow-300 text-black text-center py-2.5 px-3 text-[11px] font-black sticky top-0 z-30">🔝 Top Ad Always: {ads.top}</div>
    <div className="bg-black text-white px-6 pt-6 pb-10 rounded-b-[40px]"><div className="flex justify-between items-center"><div><p className="text-[10px] tracking-[3px] opacity-60">FRESH BUSINESS</p><h1 className="font-black text-xl">Business Pro Max</h1><p className="text-[10px] opacity-60">Visa + Cookies + Social Visit + Ad Always</p></div>{isAdmin&&<button onClick={()=>setPage("admin")} className="bg-white text-black text-[10px] font-black px-4 py-2 rounded-full">ADMIN FULL CONTROL</button>}</div><div className="mt-6 grid grid-cols-2 gap-3"><div className="bg-white/10 rounded-[20px] p-4"><p className="text-[9px] opacity-60">BALANCE</p><p className="font-black text-xl">৳{user.balance}</p></div><div className="bg-white text-black rounded-[20px] p-4"><p className="text-[9px] opacity-60">PLAN</p><p className="font-black text-xs">{user.plan?`👑 ${user.plan.name}`:"No Plan"}</p></div></div></div>
    <div className="px-5 -mt-6 grid grid-cols-2 gap-3"><button onClick={()=>setPage("deposit")} className="bg-white rounded-[20px] p-5 shadow-sm flex items-center gap-3"><div className="w-11 h-11 bg-black text-white rounded-full flex items-center justify-center">+</div><div><p className="font-black text-sm">Deposit</p><p className="text-[10px] text-gray-400">Bkash/USDT</p></div></button><button className="bg-white rounded-[20px] p-5 shadow-sm flex items-center gap-3"><div className="w-11 h-11 bg-gray-100 rounded-full flex items-center justify-center">↓</div><div><p className="font-black text-sm">Withdraw</p><p className="text-[10px] text-gray-400">USDT</p></div></button></div>
    <div className="mx-5 mt-4 bg-black text-yellow-300 rounded-[20px] p-5 text-center border-2 border-yellow-400"><p className="text-[9px] tracking-widest opacity-60">MIDDLE AD ALWAYS - সব সময় মাঝখানে থাকবে</p><p className="font-black text-sm mt-1">📢 {ads.middle}</p></div>
    <p className="px-6 mt-6 text-[10px] font-black tracking-[2px]">NEW TASKS - Visa + FB Cookies + IG Cookies + Social Visit</p>
    <div className="px-5 mt-3 grid grid-cols-4 gap-2">
      {[{k:"fb_cookies",l:"FB Cookies"},{k:"ig_cookies",l:"IG Cookies"},{k:"social_visit",l:"Social Visit"},{k:"visa",l:"Visa Service"},{k:"gmail",l:"Gmail Sell"},{k:"facebook",l:"FB Sell"},{k:"coin",l:"Coin Sell"},{k:"social_visit",l:"Video Like"}].map(it=><button key={it.k+it.l} onClick={()=>{setPage("tasks"); setCat(it.k)}} className={`bg-white rounded-[18px] py-4 flex flex-col items-center gap-1 shadow-sm border ${(features as any)[it.k]?"":"opacity-30"}`}><div className="w-10 h-10 bg-black text-white rounded-xl flex items-center justify-center text-[9px] font-black">{it.k[0].toUpperCase()}</div><p className="text-[8px] font-bold text-center leading-[9px]">{it.l}</p></button>)}
    </div>
    {page==="tasks"&&<div className="fixed inset-0 bg-[#f5f5f5] z-40 overflow-auto pb-20"><div className="bg-black text-white p-4 flex justify-between"><button onClick={()=>setPage("home")} className="bg-white/20 px-3 py-1.5 rounded-full text-xs">← Back</button><b className="uppercase text-sm">{cat.replace("_"," ")} Tasks</b><span className="w-10"></span></div><div className="bg-yellow-300 text-center py-2 text-[11px] font-bold">🔝 Top Ad Always: {ads.top}</div><div className="bg-black text-yellow-300 m-4 rounded-[20px] p-4 text-center"><p className="font-bold text-sm">📢 Middle Ad Always: {ads.middle}</p></div><div className="p-4 space-y-3">{filtered.map(t=><div key={t.id} className="bg-white rounded-[20px] p-4 shadow-sm border"><div className="flex justify-between"><span className="text-[9px] bg-black text-white px-2 py-1 rounded-full uppercase">{t.cat}</span><span className="bg-green-600 text-white px-3 py-1 rounded-full text-xs">৳{t.reward}</span></div><p className="font-bold text-sm mt-2">{t.title}</p><p className="text-[10px] text-gray-400 mt-1">Need: {t.fields}</p><button onClick={()=>{if(t.needPkg&&!user.plan) return alert("Plan Active করো"); setActive(t); setForm({}); setCount(10); setCanDo(false); setAdOpen(true)}} className="w-full mt-3 bg-black text-white py-3 rounded-full text-xs font-bold">START - 10s Ad + Receive Form</button></div>)}</div></div>}
    {page==="deposit"&&<div className="fixed inset-0 bg-white z-50 p-6 overflow-auto pb-24"><button onClick={()=>setPage("home")} className="bg-black text-white px-5 py-2 rounded-full text-sm">← Back</button><h1 className="text-xl font-black mt-5">Deposit</h1><div className="bg-yellow-300 text-center py-2 rounded-full mt-3 text-xs font-bold">🔝 {ads.top}</div><div className="flex gap-2 mt-4"><button onClick={()=>setDM("bkash")} className={`px-4 py-2 rounded-full text-xs border-2 ${dM==="bkash"?"bg-black text-white":"bg-white"}`}>Bkash</button><button onClick={()=>setDM("usdt")} className={`px-4 py-2 rounded-full text-xs border-2 ${dM==="usdt"?"bg-yellow-400":"bg-white"}`}>USDT Binance</button></div><div className="bg-black text-white rounded-[20px] p-5 mt-4 text-center"><p className="font-black break-all">{numbers[dM as keyof typeof numbers]}</p></div><input value={dA} onChange={e=>setDA(e.target.value)} placeholder="Amount" className="w-full border-2 border-black rounded-full p-3 mt-4 text-sm"/><input value={dT} onChange={e=>setDT(e.target.value)} placeholder="TrxID / Hash" className="w-full border-2 border-black rounded-full p-3 mt-2 text-sm"/><button onClick={()=>{if(!dA||!dT) return alert("Amount+TrxID দাও"); const req={id:Date.now(),email:user.email,method:dM,amount:Number(dA),trx:dT,toNumber:numbers[dM as keyof typeof numbers],status:"pending"}; const nd=[...deps,req]; setDeps(nd); save({deps:nd}); alert("Deposit Request Sent - Admin Accept করলে Balance যোগ হবে"); setPage("home")}} className="w-full mt-4 bg-black text-white py-3 rounded-full font-black">Submit Deposit</button><div className="mt-6 bg-black text-yellow-300 rounded-[20px] p-4 text-center"><p className="text-sm font-bold">📢 {ads.middle}</p><p className="text-[10px]">Middle Ad Always</p></div></div>}
    {adOpen&&active&&<div className="fixed inset-0 bg-black/80 flex items-center justify-center p-4 z-[70] overflow-auto"><div className="bg-white rounded-[32px] w-full max-w-sm p-6"><h2 className="font-black text-sm">10s Ad - {ads.task} - {count}s</h2><div className="bg-yellow-50 border-2 border-dashed rounded-[20px] p-4 mt-3"><p className="text-xs font-bold">{ads.task}</p><div className="w-full bg-gray-200 h-2 rounded-full mt-2"><div className="bg-black h-2 rounded-full" style={{width:`${(10-count)*10}%`}}></div></div></div><p className="text-3xl font-black mt-4 text-center">{count>0?count:"✅ Ad Done"}</p>{canDo&&<div className="mt-5"><p className="text-xs font-black">📥 Receive Form - {active.title}</p><p className="text-[10px] text-gray-500">Need: {active.fields}</p>{active.fields.split(",").map((f:string)=><input key={f} value={form[f]||""} onChange={e=>setForm({...form,[f]:e.target.value})} placeholder={f+" লিখো"} className="w-full border-2 border-black rounded-full p-3 mt-2 text-xs"/>)}<button onClick={()=>{if(Object.values(form).some((v:any)=>!v)) return alert("সব Field পূরণ করো"); const sub={id:Date.now(),email:user.email,cat:active.cat,title:active.title,reward:active.reward,data:form,[STRIPPED] const nd=[...subs,sub]; setSubs(nd); save({subs:nd}); alert(`Submitted - Admin Receive করবে ৳${active.reward}`); setAdOpen(false); setForm({})}} className="w-full mt-5 bg-black text-white py-4 rounded-full font-black">Submit - Admin Receive করবে ৳{active.reward}</button></div>}{!canDo&&<button disabled className="w-full mt-5 bg-gray-200 text-gray-400 py-3 rounded-full font-bold">Wait {count}s - Ad দেখো</button>}</div></div>}
    <div className="fixed bottom-0 left-0 right-0 bg-white border-t rounded-t-[28px] flex justify-around items-center py-3 shadow-[0_-10px_30px_rgba(0,0,0,0.1)]"><button onClick={()=>setPage("home")} className="flex flex-col items-center"><span className="text-xl">🏠</span><span className="text-[9px] font-black">Home</span></button><button onClick={()=>{setPage("tasks"); setCat("fb_cookies")}} className="flex flex-col items-center opacity-60"><span className="text-xl">📋</span><span className="text-[9px]">Tasks</span></button><button onClick={()=>setPage("deposit")} className="flex flex-col items-center opacity-60"><span className="text-xl">💰</span><span className="text-[9px]">Wallet</span></button><button className="flex flex-col items-center opacity-60"><span className="te
